export const textNode=value=>({type:"text",value});
export const fractionNode=()=>({type:"fraction",numerator:[],denominator:[]});
export const mixedFractionNode=()=>({type:"mixedFraction",integer:[],numerator:[],denominator:[]});
export const powerNode=()=>({type:"power",base:[],exponent:[]});
export const sqrtNode=()=>({type:"sqrt",radicand:[]});
export const nthRootNode=()=>({type:"nthRoot",index:[],radicand:[]});
export function serializeNodes(nodes){return nodes.map(n=>{switch(n.type){case"text":return n.value;case"fraction":return`(${serializeNodes(n.numerator)})/(${serializeNodes(n.denominator)})`;case"mixedFraction":return`${serializeNodes(n.integer)}+(${serializeNodes(n.numerator)})/(${serializeNodes(n.denominator)})`;case"power":return`(${serializeNodes(n.base)})^(${serializeNodes(n.exponent)})`;case"sqrt":return`sqrt(${serializeNodes(n.radicand)})`;case"nthRoot":return`root(${serializeNodes(n.index)},${serializeNodes(n.radicand)})`;default:return""}}).join("")}
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
export function renderNodes(nodes,activeArray){return nodes.map(n=>{if(n.type==="text")return`<span class="math-text">${esc(n.value)}</span>`;if(n.type==="fraction"){const na=activeArray===n.numerator?" active-slot":"",da=activeArray===n.denominator?" active-slot":"";return`<span class="math-fraction"><span class="math-numerator${na}">${renderNodes(n.numerator,activeArray)||"□"}</span><span class="math-denominator${da}">${renderNodes(n.denominator,activeArray)||"□"}</span></span>`}if(n.type==="mixedFraction")return`<span class="math-mixed"><span>${renderNodes(n.integer,activeArray)||"□"}</span><span class="math-fraction"><span class="math-numerator">${renderNodes(n.numerator,activeArray)||"□"}</span><span class="math-denominator">${renderNodes(n.denominator,activeArray)||"□"}</span></span></span>`;if(n.type==="power")return`<span class="math-power"><span>${renderNodes(n.base,activeArray)||"□"}</span><sup>${renderNodes(n.exponent,activeArray)||"□"}</sup></span>`;if(n.type==="sqrt")return`<span class="math-root">√<span class="radicand">${renderNodes(n.radicand,activeArray)||"□"}</span></span>`;if(n.type==="nthRoot")return`<span class="math-root"><sup>${renderNodes(n.index,activeArray)||"□"}</sup>√<span class="radicand">${renderNodes(n.radicand,activeArray)||"□"}</span></span>`;return""}).join("")}
