class EngineError extends Error { constructor(code){ super(code); this.code=code; } }
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a||1};
const safeInt=Number.isSafeInteger;
const norm=(n,d)=>{if(d===0)throw new EngineError("DIVISION_BY_ZERO");if(!safeInt(n)||!safeInt(d))return null;if(d<0){n=-n;d=-d}const g=gcd(n,d);const nn=n/g,dd=d/g;return safeInt(nn)&&safeInt(dd)?{n:nn,d:dd}:null};
const addR=(a,b)=>norm(a.n*b.d+b.n*a.d,a.d*b.d),subR=(a,b)=>norm(a.n*b.d-b.n*a.d,a.d*b.d),mulR=(a,b)=>norm(a.n*b.n,a.d*b.d),divR=(a,b)=>norm(a.n*b.d,a.d*b.n);
const powR=(a,p)=>{if(!Number.isInteger(p))return null;if(p===0)return{n:1,d:1};if(p<0){const q=powR(a,-p);return q?norm(q.d,q.n):null}const n=a.n**p,d=a.d**p;return Number.isFinite(n)&&Number.isFinite(d)?norm(n,d):null};
const exactString=r=>r?(r.d===1?String(r.n):`${r.n}/${r.d}`):undefined;
function decimalRational(raw){if(/[eE]/.test(raw))return null;if(!raw.includes(".")){const n=Number(raw);return safeInt(n)?{n,d:1}:null}const[i,f=""]=raw.split("."),d=10**f.length,n=Number(i||"0")*d+(Number(i||"0")<0?-Number(f):Number(f));return safeInt(n)&&safeInt(d)?norm(n,d):null}
function tokenize(input){const out=[];let i=0;input=input.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-");while(i<input.length){const c=input[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){const s=i++;while(i<input.length&&/[0-9.]/.test(input[i]))i++;if(/[eE]/.test(input[i]||"")){i++;if(/[+-]/.test(input[i]||""))i++;while(/[0-9]/.test(input[i]||""))i++}const raw=input.slice(s,i),v=Number(raw);if(!Number.isFinite(v))throw new EngineError("INVALID_EXPRESSION");out.push({t:"num",v,raw});continue}if(/[A-Za-zπ]/.test(c)){const s=i++;while(i<input.length&&/[A-Za-z0-9_π]/.test(input[i]))i++;out.push({t:"id",v:input.slice(s,i)});continue}if("+-*/^!".includes(c)){out.push({t:"op",v:c});i++;continue}if(c==="("||c===")"||c===","){out.push({t:c});i++;continue}throw new EngineError("INVALID_EXPRESSION")}out.push({t:"eof"});return out}
const V=(num,rat=null)=>({num,rat});
class Parser{
 constructor(source,ctx){this.ts=tokenize(source);this.p=0;this.ctx=ctx} peek(){return this.ts[this.p]} take(){return this.ts[this.p++]}
 parse(){const v=this.add();if(this.peek().t!=="eof")throw new EngineError("INVALID_EXPRESSION");return v}
 add(){let l=this.mul();while(this.peek().t==="op"&&["+","-"].includes(this.peek().v)){const op=this.take().v,r=this.mul();l=V(op==="+"?l.num+r.num:l.num-r.num,l.rat&&r.rat?(op==="+"?addR(l.rat,r.rat):subR(l.rat,r.rat)):null)}return l}
 mul(){let l=this.power();while(this.peek().t==="op"&&["*","/"].includes(this.peek().v)){const op=this.take().v,r=this.power();if(op==="/"&&r.num===0)throw new EngineError("DIVISION_BY_ZERO");l=V(op==="*"?l.num*r.num:l.num/r.num,l.rat&&r.rat?(op==="*"?mulR(l.rat,r.rat):divR(l.rat,r.rat)):null)}return l}
 power(){let l=this.unary();if(this.peek().t==="op"&&this.peek().v==="^"){this.take();const r=this.power(),num=Math.pow(l.num,r.num);l=V(num,l.rat&&r.rat&&r.rat.d===1?powR(l.rat,r.rat.n):null)}return l}
 unary(){if(this.peek().t==="op"&&["+","-"].includes(this.peek().v)){const o=this.take().v,v=this.unary();return o==="-"?V(-v.num,v.rat?{n:-v.rat.n,d:v.rat.d}:null):v}return this.post()}
 post(){let v=this.primary();while(this.peek().t==="op"&&this.peek().v==="!"){this.take();if(!Number.isInteger(v.num)||v.num<0||v.num>170)throw new EngineError("DOMAIN_ERROR");let n=1;for(let i=2;i<=v.num;i++)n*=i;v=V(n,safeInt(n)?{n,d:1}:null)}return v}
 primary(){const x=this.take();if(x.t==="num")return V(x.v,decimalRational(x.raw));if(x.t==="("){const v=this.add();if(this.take().t!==")")throw new EngineError("INVALID_EXPRESSION");return v}if(x.t==="id"){const id=x.v.toLowerCase();if(id==="pi"||id==="π")return V(Math.PI,null);if(id==="e")return V(Math.E,null);if(id==="ans")return V(Number(this.ctx.ans??0),decimalRational(String(this.ctx.ans??0)));if(this.take().t!=="(")throw new EngineError("INVALID_EXPRESSION");const args=[this.add()];while(this.peek().t===","){this.take();args.push(this.add())}if(this.take().t!==")")throw new EngineError("INVALID_EXPRESSION");return this.call(id,args)}throw new EngineError("INVALID_EXPRESSION")}
 call(name,args){const one=()=>{if(args.length!==1)throw new EngineError("INVALID_EXPRESSION");return args[0].num},two=()=>{if(args.length!==2)throw new EngineError("INVALID_EXPRESSION");return[args[0].num,args[1].num]},tr=x=>this.ctx.angleMode==="DEG"?x*Math.PI/180:this.ctx.angleMode==="GRAD"?x*Math.PI/200:x,fr=x=>this.ctx.angleMode==="DEG"?x*180/Math.PI:this.ctx.angleMode==="GRAD"?x*200/Math.PI:x;switch(name){case"sin":return V(Math.sin(tr(one())));case"cos":return V(Math.cos(tr(one())));case"tan":{const angle=tr(one());if(Math.abs(Math.cos(angle))<1e-14)throw new EngineError("DOMAIN_ERROR");return V(Math.tan(angle));}case"asin":{const x=one();if(x<-1||x>1)throw new EngineError("DOMAIN_ERROR");return V(fr(Math.asin(x)))}case"acos":{const x=one();if(x<-1||x>1)throw new EngineError("DOMAIN_ERROR");return V(fr(Math.acos(x)))}case"atan":return V(fr(Math.atan(one())));case"sinh":return V(Math.sinh(one()));case"cosh":return V(Math.cosh(one()));case"tanh":return V(Math.tanh(one()));case"pow10":return V(Math.pow(10,one()));case"exp":return V(Math.exp(one()));case"log":{const x=one();if(x<=0)throw new EngineError("DOMAIN_ERROR");return V(Math.log10(x))}case"ln":{const x=one();if(x<=0)throw new EngineError("DOMAIN_ERROR");return V(Math.log(x))}case"sqrt":{const x=one();if(x<0)throw new EngineError("DOMAIN_ERROR");const n=Math.sqrt(x);return V(n,Number.isInteger(n)?{n,d:1}:null)}case"abs":{const x=args[0];return V(Math.abs(x.num),x.rat?{n:Math.abs(x.rat.n),d:x.rat.d}:null)}case"root":{const[n,x]=two();if(n===0||(x<0&&Math.abs(n%2)!==1))throw new EngineError("DOMAIN_ERROR");return V(x<0?-Math.pow(-x,1/n):Math.pow(x,1/n))}case"ncr":case"npr":{let[n,r]=two();if(!Number.isInteger(n)||!Number.isInteger(r)||n<0||r<0||r>n)throw new EngineError("DOMAIN_ERROR");let v=1;if(name==="npr"){for(let i=0;i<r;i++)v*=n-i}else{r=Math.min(r,n-r);for(let i=1;i<=r;i++)v=v*(n-r+i)/i}return V(v,safeInt(v)?{n:v,d:1}:null)}default:throw new EngineError("UNSUPPORTED_OPERATION")}}
}
export function evaluateExpression(source,context={angleMode:"DEG",ans:"0"}){if(!source?.trim())return{kind:"error",code:"INVALID_EXPRESSION"};try{const v=new Parser(source,{angleMode:context.angleMode??"DEG",ans:context.ans??"0"}).parse();if(!Number.isFinite(v.num))return{kind:"error",code:"DOMAIN_ERROR"};return{kind:"value",numeric:v.num,exact:exactString(v.rat)}}catch(e){if(e instanceof EngineError)return{kind:"error",code:e.code};return{kind:"error",code:"INVALID_EXPRESSION"}}}
